import { Project } from './ProjectList';

export const projectData: Project[] = [
    {
        id: 1,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 2,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 10,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 3,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 9,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 4,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 5,
        activity: '해커톤',
        outPut: 'ANDROID',
        serviceName: '멋사 홈페이지',
        ordinal: 10,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 6,
        activity: '해커톤',
        outPut: 'ANDROID',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 7,
        activity: '해커톤',
        outPut: 'ANDROID',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 8,
        activity: '해커톤',
        outPut: 'ANDROID',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 9,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 10,
        activity: '해커톤',
        outPut: 'IOS',
        serviceName: '멋사 홈페이지',
        ordinal: 9,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 11,
        activity: '해커톤',
        outPut: 'IOS',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 12,
        activity: '해커톤',
        outPut: 'IOS',
        serviceName: '멋사 홈페이지',
        ordinal: 7,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 13,
        activity: '해커톤',
        outPut: 'IOS',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 14,
        activity: '해커톤',
        outPut: 'IOS',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 15,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 6,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 16,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 17,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 18,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 19,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
    {
        id: 20,
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTech: ['java', 'javascript'],
        imageUrl: ['', ''],
        members: [{ userId: 1, name: 'user' }],
    },
];
