import { ProjectEach } from './register/ProjectRegister';

export const projectData: ProjectEach[] = [
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 10,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 9,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'ANDROID',
        serviceName: '멋사 홈페이지',
        ordinal: 10,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'ANDROID',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'ANDROID',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'ANDROID',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'IOS',
        serviceName: '멋사 홈페이지',
        ordinal: 9,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'IOS',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'IOS',
        serviceName: '멋사 홈페이지',
        ordinal: 7,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'IOS',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'IOS',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 6,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
    {
        activity: '해커톤',
        outPut: 'WEB',
        serviceName: '멋사 홈페이지',
        ordinal: 11,
        univ: '홍익대학교',
        startDate: '2023-11-11',
        endDate: '2023-12-23',
        description: '서비스(프로젝트)에 대한 소개',
        content: '두줄까지 표시되고, 넘치면 궁시렁 콩시렁',
        productionUrl: 'https://www.likelion.university',
        projectTeches: 'java,javascript',
        imageUrl: ['', ''],
        members: [1],
    },
];
