export const AccessToken =
    'eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJMaWtlbGlvblVuaXYiLCJzdWIiOiIyIiwiaWF0IjoxNzAyOTk2Nzg4LCJleHAiOjE3MDQyMDYzODgsInR5cGUiOiJBY2Nlc3NUb2tlbiIsInJvbGUiOiJHVUVTVCJ9.DnZ-leBl4Unj4U3tPUpEOX-BUrHSvYOpqe4XqhILm8SEWkbdaHeYrbaI7cLWokI_PNsJYGJxSBuJ0sEt4tSUMw';
export const RefreshToken =
    'eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJMaWtlbGlvblVuaXYiLCJzdWIiOiIyIiwiaWF0IjoxNzAyOTk2Nzg4LCJleHAiOjE3MDQyMDYzODgsInR5cGUiOiJSZWZyZXNoVG9rZW4iLCJyb2xlIjoiR1VFU1QifQ.HtTF9deEo7Gm2PIHOSwM3YuHnCqfdutCvAUhDNLFSnkdw8FO6kYHp1TQjAQpxrwSWH2___vqZ-psJSMzraE6KQ';
