export const AccessToken =
    'eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJMaWtlbGlvblVuaXYiLCJzdWIiOiIyIiwiaWF0IjoxNzAyOTk5NDYzLCJleHAiOjE3MDQyMDkwNjMsInR5cGUiOiJBY2Nlc3NUb2tlbiIsInJvbGUiOiJHVUVTVCJ9.c6ijvuhIluD_PWw8S8xGT-2IO5uAvO-_fd30RqNalTj43fny99ieQEn5yrZLXTa4qw-Ln_S-iZ1VoCgfwLi4Ig';
export const RefreshToken =
    'eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJMaWtlbGlvblVuaXYiLCJzdWIiOiIyIiwiaWF0IjoxNzAyOTk2Nzg4LCJleHAiOjE3MDQyMDYzODgsInR5cGUiOiJSZWZyZXNoVG9rZW4iLCJyb2xlIjoiR1VFU1QifQ.HtTF9deEo7Gm2PIHOSwM3YuHnCqfdutCvAUhDNLFSnkdw8FO6kYHp1TQjAQpxrwSWH2___vqZ-psJSMzraE6KQ';
